name: Emojified Unit Tests
on:
  push:
    branches:
      - main
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install deps
        run: yarn
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build chrome extension
        run: yarn build
  upload-extension:
    runs-on: ubuntu-latest
    needs: [setup, build]
    steps:
      - name: Upload extension
        uses: actions/upload-artifact@v3
        with:
          name: ${{ date +"%Y-%m-%d_%H.%M"}}
          path: ./dist
