name: Emojified Unit Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
permissions: read-all
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install deps
        run: yarn
  unit-test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup Node and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install deps
        run: yarn

      - name: Run unit tests
        run: yarn test:unit
